import random
import problem_bank_helpers as pbh

def generate(data):
    data2 = pbh.create_data2()
    
    # Part 1 possible answers
    data2["params"]["part1"]["ans1"]["value"] = "A"
    data2["params"]["part1"]["ans1"]["correct"] = False
    
    data2["params"]["part1"]["ans2"]["value"] = "B"
    data2["params"]["part1"]["ans2"]["correct"] = True
    
    data2["params"]["part1"]["ans3"]["value"] = "C"
    data2["params"]["part1"]["ans3"]["correct"] = False
    
    data2["params"]["part1"]["ans4"]["value"] = "D"
    data2["params"]["part1"]["ans4"]["correct"] = False

    # Part 2 possible answers
    data2["params"]["part2"]["ans1"]["value"] = "A"
    data2["params"]["part2"]["ans1"]["correct"] = False
    
    data2["params"]["part2"]["ans2"]["value"] = "B"
    data2["params"]["part2"]["ans2"]["correct"] = True
    
    data2["params"]["part2"]["ans3"]["value"] = "C"
    data2["params"]["part2"]["ans3"]["correct"] = False
    
    data2["params"]["part2"]["ans4"]["value"] = "D"
    data2["params"]["part2"]["ans4"]["correct"] = False

    # Part 3 possible answers
    data2["params"]["part3"]["ans1"]["value"] = "The net centripetal force is generated by friction."
    data2["params"]["part3"]["ans1"]["correct"] = False
    
    data2["params"]["part3"]["ans2"]["value"] = "The net centripetal force is generated by the normal force and gravity."
    data2["params"]["part3"]["ans2"]["correct"] = False
    
    data2["params"]["part3"]["ans3"]["value"] = "The frictional force is static and is generated in the normal direction."
    data2["params"]["part3"]["ans3"]["correct"] = False
    
    data2["params"]["part3"]["ans4"]["value"] = "The frictional force is static and is generated up the incline."
    data2["params"]["part3"]["ans4"]["correct"] = True
    
    # Update the data object with a new dict
    data.update(data2)
    
def prepare(data):
    pass
    
def parse(data):
    pass
    
def grade(data):
    pass
    
